version: '3'

services:
  backend:
    tty: true
    volumes:
      - .:/workspace:cached
      - ${SSH_KEY_PATH:-~/.ssh/}:/.ssh/:ro
    command: /bin/sh -c "while sleep 1000; do :; done"

  #frontend:
  #  volumes:
  #    - .:/workspace:cached
  #  command: /bin/sh -c "while sleep 1000; do :; done"
#
    #build: ./frontend
    #tty: true
    #ports:
    #  - 3000:3000