name: Build and Deploy

on:
  push:
    branches:
      - main  # Runs the action on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Use the Azure Service Principal credentials stored in secrets
          
      # Login to ACR
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
            
      # Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaaliplatta:latest -f Dockerfile.prod .
      
      # Pust the image to ACR
      - name: Push image to ACR
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaaliplatta:latest

      # Deploy to Azure App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: vaaliplatta  # Azure App Service name
          slot-name: production  # Change this if you use a deployment slot
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/vaaliplatta:latest
      
      # Log out
      - name: Azure logout
        run: |
          az logout
